module.exports = {
	"cv": "http://cv.ericmc.co/",
	"github": "https://github.com/edm00se",
	"gh": "https://github.com/edm00se",
        "em": "https://ericmccormick.io",
        "emoji": "https://ericmccormick.io",
	"repos": "https://github.com/edm00se",
	"blog": "https://edm00se.io/",
	"devblog": "https://edm00se.io/",
	"iot-pi-blog": "https://edm00se.github.io/iot-pi/",
	"iot-pi": "https://edm00se.github.io/iot-pi/",
	"about": "http://about.me/EricMcCormick",
	"aboutme": "http://about.me/EricMcCormick",
	"about.me": "http://about.me/EricMcCormick",
	"twitter": "https://twitter.com/edm00se",
	"so": "https://stackoverflow.com/users/1720082/eric-mccormick",
	"stackoverflow": "https://stackoverflow.com/users/1720082/eric-mccormick",
	"linkedin": "https://www.linkedin.com/in/emccormick",
	"npm": "https://www.npmjs.com/~edm00se",
	"instagram": "https://www.instagram.com/edm00se/",
	"ibm": "https://www.ibm.com/developerworks/community/profiles/html/profileView.do?key=1dea34d1-c338-4c44-950f-54c4f49f9ba3"
};
